version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: lame_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: musicdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./music-backend
    container_name: lame_backend
    restart: always
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "3000:3000"

  frontend:
    build: ./music-frontend
    container_name: lame_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mysql_data:
